data:
  lr: 0.001
  lr_f: 0.01
  num_hidden: 512
  num_heads: 4
  num_layers: 4
  weight_decay: 2e-4
  weight_decay_f: 1e-4
  max_epoch: 2000
  max_epoch_f: 300
  mask_rate: 0.1
  num_layers: 2
  encoder: gcn
  decoder: mlp
  activation: prelu
  in_drop: 0.2
  attn_drop: 0.1
  linear_prob: True
  loss_fn: sce
  drop_edge_rate: 0.0
  optimizer: adamw
  replace_rate: 0.0
  alpha_l: 3
  scheduler: True
